image: docker:18.09.7-dind

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: "registry.gitlab.com/bebuy.vn/clients/daidung/back-office"

stages:
  # - prepare
  - build
  # - lint
  # - test
  # - deploy

.build_image:
  tags:
    - bebuy-gitlab-ci
  before_script:
    - docker login registry.gitlab.com -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

build-service:
  stage: build
  only:
    - master

  extends:
    - .build_image
  
  script:
    - docker build -t $REGISTRY .  --no-cache
    - docker tag $REGISTRY $REGISTRY:latest
    - docker push $REGISTRY:latest
